# Generated by Django 3.2 on 2021-04-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default="'Margaret's Blog", max_length=255),
        ),
    ]
